/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zwc' at '17-1-31 下午3:25' with Gradle 2.14.1
 *
 * @author zwc, @date 17-1-31 下午3:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
